### ISSUE TITLE
NTR: Request for S27 2-ethylhexyl trans-4-methoxycinnamate

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S27#11]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>2-ethylhexyl trans-4-methoxycinnamate <p><b>Definition</b><p> A cinnamate ester often used as a UV filter/light absorber in personal care products such as sunscreens.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created:
CS004349	2-ethylhexyl trans-4-methoxycinnamate
