### ISSUE TITLE
NTR: Request for S27 tonalid

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S27#12]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>tonalid <p><b>Definition</b><p> A synthetic fragrance used in the cosmetic industry. Also known as 1-(5,6,7,8-tetrahydro-3,5,5,6,8,8-hexamethyl-2-naphthyl)ethan-1-one and 2-Acetyl-3,5,5,6,8,8-hexamethyl-5,6,7,8- tetrahydronaphthalene, among other names.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
term created:
CS004348	tonalid
