### ISSUE TITLE
NTR: 1-phenanthrol [CAS2433-56-9]

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/S27#18]
### Term name (PrefLabel) - REQUIRED
[Preferred label for the new term - this can be a substance or a mixture of substances]

1-phenanthrol

### CAS Registry Number - REQUIRED
[Provide the CASRN for the chemical entity - if not applicable please write n/a] 

2433-56-9

### Definition - REQUIRED
[Please enter a proposed short description of the new entity] 

A phenanthrol and a metabolite of phenanthrene that can be detected in urine of persons exposed to PAHs. It can be used as a marker for PAH pollution measured in marine fish bile.

### Sources/references - REQUIRED
[Please enter a link to a reference source]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27528
https://jira.ceh.ac.uk/browse/BODCNVS-1384

### Mapping to external terminologies - OPTIONAL
[We map to ChEBI so please provide the link to ChEBI if known or links to other relevant external resources - enter one URI or a list of URIs]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27528

**Comment by gwemon** [comment]
@roswri I'd spell out Polycyclic aromatic hydrocarbons (PAHs) in the definition. Also, P01 created for this new substance will need to be narrow concepts of P02=[BCAH](http://vocab.nerc.ac.uk/collection/P02/current/BCAH/) when measured in biota I think as that would be the most closely associated P02 grouping.

**Comment by roswri** [comment]
New term created:
CS004457 - 1-phenanthrol [http://vocab.nerc.ac.uk/collection/S27/current/CS004457] (will close ticket tomorrow once term goes live on NVS)
