### ISSUE TITLE
NTR: New chemical substances for SIMM work

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S27#26]
### Term name (PrefLabel)
2,3,3',4,4',5,5',6-octabromodiphenyl ether
### Alternative name (AltLabel)
BDE205
### CAS Registry Number
446255-56-7
### Definition
One of 209 congeners of polybrominated diphenyl ether (PBDE). 
### Sources/references
https://www.chemicalbook.com/ChemicalProductProperty_EN_CB2837352.htm
### Mapping to external terminologies 
NA

---------------------------------------------------------------------------------------------------------------------------------------
### Term name (PrefLabel)
di-n-hexyl phthalate
### Alternative name (AltLabel)
NA
### CAS Registry Number
84-75-3
### Definition
An organic compound with formula C20H30O4 belonging to a group of chemicals used to make plastics more durable. Phthalates are esters of phthalic acid.
### Sources/references
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34678
### Mapping to external terminologies
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34678 

---------------------------------------------------------------------------------------------------------------------------------------
### Term name (PrefLabel)
diheptyl phthalate
### Alternative name (AltLabel)
NA
### CAS Registry Number
3648-21-3
### Definition
An organic compound with formula C22H34O4 belonging to a group of chemicals used to make plastics more durable. Phthalates are esters of phthalic acid.
### Sources/references
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34677
### Mapping to external terminologies
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:34677

**Comment by Osanna123** [comment]
CAS 446255-56-7: https://vocab.ices.dk/?codeguid=850c9f59-68dc-4cc4-b49a-9743eb529a95
CAS 84-75-3: https://vocab.ices.dk/?codeguid=f2ef9bec-8be1-4e2d-b006-4514533d1552
CAS 3648-21-3 NA in ICES vocab

**Comment by gwemon** [comment]
Hello @Osanna123 Up until now we've mapped our S27 concept to the ICES PARAM concepts via the URLs of the form: http://vocab.ices.dk/services/rdf/collection/PARAM/
Can we continue doing this or do we need to switch to the codeguid links?

**Comment by Osanna123** [comment]
Thanks @gwemon , you can continue using the links as before. :)

**Comment by danibodc** [comment]
These terms have now been loaded and are queued for publication on the NVS.

**Comment by danibodc** [comment]
Terms are now live on the NVS:
https://vocab.nerc.ac.uk/collection/S27/current/CS004481/
https://vocab.nerc.ac.uk/collection/S27/current/CS004482/
https://vocab.nerc.ac.uk/collection/S27/current/CS004483/
