### ISSUE TITLE
NTR: 2 new substances - benzotriazole and citalopram [BODCNVS-2167]

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S27#29]
### Term name (PrefLabel) - REQUIRED
benzotriazole
### CAS Registry Number - REQUIRED
95-14-7
### Definition - REQUIRED
The simplest member of the class of benzotriazoles that consists of a benzene nucleus fused to a 1H-1,2,3-triazole ring. It has a ariety of uses, for instance as a corrosion inhibitor for copper. It has a molecular formula C6H5N3.
### Sources/references - REQUIRED
NA
### Mapping to external terminologies - OPTIONAL
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:75331
https://pubchem.ncbi.nlm.nih.gov/compound/7220
### Term name (PrefLabel) - REQUIRED
citalopram
### CAS Registry Number - REQUIRED
59729-33-8
### Definition - REQUIRED
A racemate comprising equimolar amounts of (R)-citalopram and its enantiomer, escitalopram. It is used as an antidepressant, although only escitalopram is active. It has a molecular formula C20H21FN2O.
### Sources/references - REQUIRED
NA
### Mapping to external terminologies - OPTIONAL
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:3723
https://pubchem.ncbi.nlm.nih.gov/compound/2771

**Comment by danibodc** [comment]
Terms have now been loaded and are now live on the NVS:

CS004549	benzotriazole
CS004548	citalopram

**Comment by Osanna123** [comment]
Mapping to external terminologies: 
CS004549 benzotriazole same as https://vocab.ices.dk/?codeguid=d4629da0-722d-463d-b6b7-ddc1ffaa6bfd
CS004548 citalopram same as https://vocab.ices.dk/?codeguid=0f292382-61ca-4bb0-ac47-d1404fe83b25

**Comment by danibodc** [comment]
Thank you @Osanna123, I've added these mappings.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S27/current/CS004548/
https://vocab.nerc.ac.uk/collection/S27/current/CS004549/
