### ISSUE TITLE
Duplicate terms? (BODCNVS-754)

### ISSUE THREAD

**Issue by Osanna123** [nvs-vocabs/S27#3]
CS003521 and CS002895 point to the same combination of the hexachlorocyclohexanes.
By label, it seems that CS003521 should have pointed to CAS 608-73-1 rather than combination of 3 specific isomers

**Comment by gwemon** [comment]
Thank you @Osanna123 
I am detailing the two records with the full links below for reference: 
http://vocab.nerc.ac.uk/collection/S27/current/CS003521/
prefLabel: hexachlorocyclohexanes
altLabel: alpha+beta+gamma-hexachlorocyclohexane CAS 319-84-6+CAS 319-85-7+CAS 58-89-9
definition: A mixture of three isomers of the pesticide haxachlorocyclohexane in any proportion.

http://vocab.nerc.ac.uk/collection/S27/current/CS002895/
prefLabel: alpha-hexachlorocyclohexane+beta-hexachlorocyclohexane+gamma-hexachlorocyclohexane
altLabel: alphaHCH+betaHCH+gammaHCH
definition: A mixture of organochlorine compounds that are persistent organic pollutants.

Yes, you're right it looks like the alternative label for CS003521 is wrong and the CAS should be the generic or "technical" 608-73-1; I will correct it.

Do you have both represented as well in your ICES chemical substance vocab? i.e hexachlorocyclohexanes as a generic mixture and the mixture of the 3 isomers as specified in CS002895?

**Comment by Osanna123** [comment]
For mixtures of hexachlorocyclohexanes, we presently have only the PARAM related to 608-73-1.
https://vocab.ices.dk/?CodeID=130062

**Comment by gwemon** [comment]
The alternative label, description, and mappings to CAS and ChEBI of https://vocab.nerc.ac.uk/collection/S27/current/CS003521/ has been updated. It will be live on the NVS after our next refresh on 16/01/2021 shortly after 0200UT. 

The alternative label and description of https://vocab.nerc.ac.uk/collection/S27/current/CS002895/ have also been updated in order to be consistent with the preferred label.

**Comment by gwemon** [comment]
The update to CS003521 has not gone through as planned. It will be updated today.
