### ISSUE TITLE
NTR: 3 new S27 terms required that reference branched and linear forms

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S27#30]
### Term name (PrefLabel) - REQUIRED
perfluorodecanesulfonic acid (branched + linear)
### CAS Registry Number - REQUIRED
335-77-3
### Definition - REQUIRED
An organofluorine. The sum of all branched and linear forms.
### Sources/references - REQUIRED
https://chem.nlm.nih.gov/chemidplus/rn/335-77-3
A variant of existing term https://vocab.nerc.ac.uk/collection/S27/current/CS003707/ 
### Mapping to external terminologies - OPTIONAL
https://chem.nlm.nih.gov/chemidplus/rn/335-77-3

------------------------------------------------------------------------------------------------------

### Term name (PrefLabel) - REQUIRED
perfluorohexanesulfonic acid (branched + linear)
### CAS Registry Number - REQUIRED
355-46-4
### Definition - REQUIRED
An organofluorine. The sum of all branched and linear forms.
### Sources/references - REQUIRED
https://chem.nlm.nih.gov/chemidplus/rn/355-46-4
A variant of existing term https://vocab.nerc.ac.uk/collection/S27/current/CS003711/ 
### Mapping to external terminologies - OPTIONAL
https://chem.nlm.nih.gov/chemidplus/rn/355-46-4

------------------------------------------------------------------------------------------------------

### Term name (PrefLabel) - REQUIRED
perfluorooctanyl sulfonic acid (sum of linear isomers)
### CAS Registry Number - REQUIRED
1763-23-1
### Definition - REQUIRED
An organofluorine. The sum of all isomers with linear forms.
### Sources/references - REQUIRED
https://chem.nlm.nih.gov/chemidplus/rn/1763-23-1
A variant of existing term https://vocab.nerc.ac.uk/collection/S27/current/CS004546/ 
### Mapping to external terminologies - OPTIONAL
https://chem.nlm.nih.gov/chemidplus/rn/1763-23-1

**Comment by danibodc** [comment]
Required as part of https://github.com/nvs-vocabs/P01/issues/252

**Comment by gwemon** [comment]
@danibodc We have already mapped our S27 term: http://vocab.nerc.ac.uk/collection/S27/current/CS003707/ to ICES http://vocab.ices.dk/services/rdf/collection/PARAM/PFDS with a sameAs relationship therefore taking the approach that if linear or branched is unspecified then the term would have a mixture of both forms. This sound reasonable to me. It would be good reaching out to EMODnet chemistry or ICES about this. Please liaise with @SLBlakeman.

**Comment by Osanna123** [comment]
CAS numbers are usually including all isomer forms or are specific to a single isomer. If there are some isomers (or groups of such) without a specific CAS, we do not assign them the parent CAS. 
Thus, CAS 335-77-3 is same as ICES PARAM PFDS (branched + linear) https://vocab.ices.dk/?codeguid=328d7744-c6fd-4e62-9c12-e44c7eb60317
CAS 355-46-4 is same as PFHXS (branched + linear) https://vocab.ices.dk/?codeguid=21e111db-6e41-40c7-bab2-80397ad14052
But CAS 1763-23-1 is same as PFOS (branched + linear) https://vocab.ices.dk/?codeguid=2dfc3fd6-fb8d-41b7-bc50-527fa94ae582.
A separate PARAM n-PFOS is created for linear forms only, and no (same as) CAS link https://vocab.ices.dk/?codeguid=d0e92d5e-6d18-4786-892d-c6f3111541a1

**Comment by gwemon** [comment]
Thank you @Osanna123. We could make the mapping relationship between the grouping of linear or branched forms and the CAS number to be Broader/Narrower? It would enable us to maintain that link without stating that they are the same because they are not?

**Comment by Osanna123** [comment]
Hi @gwemon. Yes, it sounds like a good solution if you can use the broader/narrower relations in the cases for only linear or branched isomers

**Comment by danibodc** [comment]
Single new term created:
[CS004550](https://vocab.nerc.ac.uk/collection/S27/current/CS004550/) - perfluorooctanyl sulfonic acid (linear)
