### ISSUE TITLE
NTR: Batch of new S27s

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S27#33]
[CS004554](http://vocab.nerc.ac.uk/collection/S27/current/CS004554/)  - 1,1'-ethane-1,2-diylbis(pentabromobenzene)
[CS004555](http://vocab.nerc.ac.uk/collection/S27/current/CS004555/)  -   1-[2,3-dihydro-1,1,2,6-tetramethyl-3-(1-methylethyl)-1H-inden-5-yl]ethan-1-one
[CS004556](http://vocab.nerc.ac.uk/collection/S27/current/CS004556/)  - 2-(2H-benzotriazol-2-yl)-4,6-bis(1-methyl-1-phenylethyl)phenol
[CS004557](http://vocab.nerc.ac.uk/collection/S27/current/CS004557/)  - 2-(2H-benzotriazol-2-yl)-4-methylphenol
[CS004558](http://vocab.nerc.ac.uk/collection/S27/current/CS004558/)  - dioxybenzone
[CS004559](http://vocab.nerc.ac.uk/collection/S27/current/CS004559/)  - 2,4,6,8-tetramethyl-2,4,6,8-tetravinylcyclotetrasiloxane
[CS004560](http://vocab.nerc.ac.uk/collection/S27/current/CS004560/)  - homosalate
[CS004561](http://vocab.nerc.ac.uk/collection/S27/current/CS004561/)  - 3,4,5-trimethylphenyl methylcarbamate
[CS004562](http://vocab.nerc.ac.uk/collection/S27/current/CS004562/)  - 2,2'-methylenediphenol
[CS004563](http://vocab.nerc.ac.uk/collection/S27/current/CS004563/)  - 4-(αlpha,αlpha-dimethylbenzyl)phenol
[CS004564](http://vocab.nerc.ac.uk/collection/S27/current/CS004564/)  - azacyclonol
[CS004565](http://vocab.nerc.ac.uk/collection/S27/current/CS004565/)  - bis(2,6-diisopropylphenyl)carbodiimide
[CS004566](http://vocab.nerc.ac.uk/collection/S27/current/CS004566/)  - bis(2-ethylhexyl) adipate
[CS004567](http://vocab.nerc.ac.uk/collection/S27/current/CS004567/)  - bumetrizole
[CS004568](http://vocab.nerc.ac.uk/collection/S27/current/CS004568/)  - carbazole
[CS004569](http://vocab.nerc.ac.uk/collection/S27/current/CS004569/)  - chloramphenicol
[CS004570](http://vocab.nerc.ac.uk/collection/S27/current/CS004570/)  -   1-cyclopropyl-7-(4-ethylpiperazin-1-yl)-6-fluoro-4-oxo-1,4-dihydroquinoline-3-carboxylic   acid
[CS004571](http://vocab.nerc.ac.uk/collection/S27/current/CS004571/)  - mefenamic acid
[CS004572](http://vocab.nerc.ac.uk/collection/S27/current/CS004572/)  - N-1,3-dimethylbutyl-N'-phenyl-p-phenylenediamine-quinone
[CS004573](http://vocab.nerc.ac.uk/collection/S27/current/CS004573/)  - N,N-dimethyl-1-octadecanamine
[CS004574](http://vocab.nerc.ac.uk/collection/S27/current/CS004574/)  - N,N-dimethyldodecan-1-amine
[CS004575](http://vocab.nerc.ac.uk/collection/S27/current/CS004575/)  - octabenzone
[CS004576](http://vocab.nerc.ac.uk/collection/S27/current/CS004576/)  - octinoxate
[CS004577](http://vocab.nerc.ac.uk/collection/S27/current/CS004577/)  - O-desmethylvenlafaxine
[CS004578](http://vocab.nerc.ac.uk/collection/S27/current/CS004578/)  - ofloxacin
[CS004579](http://vocab.nerc.ac.uk/collection/S27/current/CS004579/)  - oxolinic acid
[CS004580](http://vocab.nerc.ac.uk/collection/S27/current/CS004580/)  - 2,3,4,5,6-pentabromotoluene
[CS004581](http://vocab.nerc.ac.uk/collection/S27/current/CS004581/)  - tramadol
[CS004582](http://vocab.nerc.ac.uk/collection/S27/current/CS004582/)  - irbesartan
[CS004583](http://vocab.nerc.ac.uk/collection/S27/current/CS004583/)  - venlafaxine
[CS004584](http://vocab.nerc.ac.uk/collection/S27/current/CS004584/)  - hexabromobenzene
[CS004585](http://vocab.nerc.ac.uk/collection/S27/current/CS004585/)  - 2,4-dihydroxybenzophenone
[CS004586](http://vocab.nerc.ac.uk/collection/S27/current/CS004586/)  - N-1,3-dimethylbutyl-N'-phenyl-p-phenylenediamine
[CS004587](http://vocab.nerc.ac.uk/collection/S27/current/CS004587/)  - 2-isopropyl-9H-thioxanthen-9-one

@MeganAnneFrench These terms have been published and will be live on the NVS from tomorrow morning. We will also map these to P36 terms.

**Comment by danibodc** [comment]
@MeganAnneFrench I forgot to add - you had requested acetaminophen, we already have 'paracetamol' in S27: https://vocab.nerc.ac.uk/collection/S27/current/CS003962/ so hopefully this one would suit?

**Comment by MeganAnneFrench** [comment]
Yes, no problem, I had searched by name or CAS in the NVS search tool, but CAS only come up if included in a P01, so I had not found it. Thanks again!

**Comment by SLBlakeman** [comment]
Hi @MeganAnneFrench,

I've linked the following S27s and P36s:

[CS004561](http://vocab.nerc.ac.uk/collection/S27/current/CS004561/) - 3,4,5-trimethylphenyl methylcarbamate to [Pesticides and biocides](http://vocab.nerc.ac.uk/collection/P36/current/PESTBI/) 
[CS004563](http://vocab.nerc.ac.uk/collection/S27/current/CS004563/) - 4-(αlpha,αlpha-dimethylbenzyl)phenol to  [Pesticides and biocides](http://vocab.nerc.ac.uk/collection/P36/current/PESTBI/) 
[CS004564](http://vocab.nerc.ac.uk/collection/S27/current/CS004564/) - azacyclonol to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004569](http://vocab.nerc.ac.uk/collection/S27/current/CS004569/) - chloramphenicol to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004570](http://vocab.nerc.ac.uk/collection/S27/current/CS004570/) - 1-cyclopropyl-7-(4-ethylpiperazin-1-yl)-6-fluoro-4-oxo-1,4-dihydroquinoline-3-carboxylic acid to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004571](http://vocab.nerc.ac.uk/collection/S27/current/CS004571/) - mefenamic acid to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004577](http://vocab.nerc.ac.uk/collection/S27/current/CS004577/) - O-desmethylvenlafaxine to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004578](http://vocab.nerc.ac.uk/collection/S27/current/CS004578/) - ofloxacin to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004579](http://vocab.nerc.ac.uk/collection/S27/current/CS004579/) - oxolinic acid to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004581](http://vocab.nerc.ac.uk/collection/S27/current/CS004581/) - tramadol to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004582](http://vocab.nerc.ac.uk/collection/S27/current/CS004582/) - irbesartan to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 
[CS004583](http://vocab.nerc.ac.uk/collection/S27/current/CS004583/) - venlafaxine to [Pharmaceuticals](http://vocab.nerc.ac.uk/collection/P36/current/PHARMS/) 

The remainder appear to all be either flame retardants or UV stabilisers, I'm not quite sure what P36 those should be linked to, if any. Do you agree with the linkages we've done? Are there any other linkages that you would suggest? 

The changes I've made will appear on the NVS in the morning.

Thanks,
Sam

**Comment by MeganAnneFrench** [comment]
Hi Sam,
I know, most of them have no P36, don't worry (it is a known issue with the
current P36s...). The only difference between your list and mine is that I
did not class CS004563 (CAS 599-64-4) as a Pesticide and biocide because it
say the following in PubChem (4-Cumylphenol | C15H16O | CID 11742 - PubChem
<https://pubchem.ncbi.nlm.nih.gov/compound/11742#section=Use-and-Manufacturing>):
"Used to make resins, insecticides, lubricants, polycarbonates, and
surfactants; [HSDB] Used as an intermediate". (i.e. it has a wider use,
"The major use of phenol, 4-(1-methyl-1-phenethyl)- (which is commonly
known as 4-cumylphenol) is as a chain terminator for polycarbonates"). In
the CONTRAST project, it is classified as "Degradant and impurity,
Solvent".
Thanks to both you and Dani for your effort!

**Comment by SLBlakeman** [comment]
Hi Megan,
That's great, thanks for letting me know. As the P36 is an emodnet chemistry vocab, I've removed the link between CS004563 and PESTBI. 
Thanks.
