### ISSUE TITLE
NTR: Inorganic phosphorus (BODCNVS-1053)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/S27#5]
### Term name (PrefLabel) - REQUIRED
Inorganic phosphorus
### CAS Registry Number - REQUIRED
7723-14-0
### Definition - REQUIRED
Inorganic phosphorus
### Sources/references - REQUIRED
eReefs
### Mapping to external terminologies - OPTIONAL
http://purl.obolibrary.org/obo/CHEBI_26082 
### ORCID - OPTIONAL
orcid.org/0000-0002-3884-3420

**Comment by JordanAthertonNOC** [comment]
One new S27 term created:

CS004372	
inorganic phosphorus
Atomic phosphorus that is incorporated into any compound that is not a covalently-bonded carbon compound. Includes phosphate, hydrogen phosphate, dihydrogen phosphate, and phosphoric acid.

https://vocab.nerc.ac.uk/collection/S27/current/CS004372/
