### ISSUE TITLE
NTR: Aragonite (BODCNVS-1051)

### ISSUE THREAD

**Issue by dr-shorthair** [nvs-vocabs/S27#6]
### Term name (PrefLabel) - REQUIRED
Aragonite
### CAS Registry Number - REQUIRED
14791-73-2
### Definition - REQUIRED
A specific crystalline form of CaCO3 - see https://en.wikipedia.org/wiki/Aragonite 
### Sources/references - REQUIRED
https://en.wikipedia.org/wiki/Aragonite (required for eReefs)
### Mapping to external terminologies - OPTIONAL
http://purl.obolibrary.org/obo/CHEBI_52239
### ORCID - OPTIONAL
orcid.org/0000-0002-3884-3420

**Comment by gwemon** [comment]
@dr-shorthair  new term added: http://vocab.nerc.ac.uk/collection/S27/current/CS003956/
