### ISSUE TITLE
NTR: Request for S27 Inorganic mercury

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S27#8]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Inorganic mercury <p><b>Definition</b><p> Atomic mercury that is incorporated into any compound that is not a covalently-bonded carbon compound. Includes all oxidation states.<p><H2> Optional </H2><p><b>Synonym or acronym (AltLabel)</b><p> inorganic_Hg<p>

**Comment by roswri** [comment]
Term Created:
CS004346	inorganic mercury
