### ISSUE TITLE
NTR: Request for S27 galaxolide

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S27#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>galaxolide <p><b>Definition</b><p> A synthetic fragrance used in the cosmetic industry. Also known as 1,3,4,6,7,8-hexahydro-4,6,6,7,8,8-hexamethylindeno[5,6-c]pyran and 1,3,4,6,7,8-Hexahydro-4,6,6,7,8,8-hexamethylcyclopenta(g)-2-benzopyran, among other names.<p><H2> Optional </H2><p>

**Comment by roswri** [comment]
Term created: 
CS004347	galaxolide
